# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: '3'

tasks:

  _main:
    cmds:
      - task: install_vscode
      - task: enable_code_tunnel_service

  install_vscode:
    cmds:
      - sudo snap install code --classic
    status:
      - test -f /snap/bin/code

  enable_code_tunnel_service:
    cmds:
      - sudo loginctl enable-linger azureuser
      - code tunnel service install
      - echo "Make sure log does not contain 'The authorization request is still pending', otherwise run task reinstall_code_tunnel_service."
      - code tunnel service log

  reinstall_code_tunnel_service:
    cmds:
      - code tunnel service uninstall
      - code tunnel service install
      - code tunnel service log
    # check log of code tunnel service, check last 5 lines, give error if it contains the given string
    status:
      - '{ timeout 1s code tunnel service log; } | tail -n 5 | grep -qv "The authorization request is still pending"'
